/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopfinalproject;

/**
 *
 * @author ABDULLAH ABBASI
 */
public class AdjointForm extends javax.swing.JFrame {
String x;
    /**
     * Creates new form AdjointForm
     */
    public AdjointForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Adjoint of matrix ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(" " +Execution.getm());
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        if(Execution.op1==1)
        x=adj2x2(Execution.a11,Execution.a12 ,Execution.a21,Execution.a22);
        else
        x=adj3x3(Execution.a11,Execution.a12,Execution.a13,Execution.a21,Execution.a22,Execution.a23,Execution.a31,Execution.a32,Execution.a33);
        jTextArea2.setText(" "+x);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
   public String adj3x3(double a11,double a12,double a13,double a21,double a22,double a23, double a31, double a32, double a33){
        double e11=a22*a33-a23*a32;
        double e12=a32*a13-a33*a12;
        double e13=a12*a23-a13*a22;
        double e21=a23*a31-a21*a33;
        double e22=a33*a11-a31*a13;
        double e23=a13*a21-a11*a22;
        double e31=a21*a32-a22*a31;
        double e32=a31*a12-a32*a11;
        double e33=a11*a22-a12*a21;
        String x=
        ("Final form of Adjoint:")+"\n"+
        (e11+"    "+e12+"    "+e13)+"\n"+
                (e21+"    "+e22+"    "+e23)+"\n"+
                (e31+"    "+e32+"    "+e33);
        return x;
    }
      
    
    public String AdjForms3x3(double a11,double a12,double a13,double a21,double a22,double a23, double a31, double a32, double a33){
        String x="First form:"+"\n"+
  (a11+"    "+a12+"    "+a13+"    "+a11+"    "+a12)+"\n"+
   (a21+"    "+a22+"    "+a23+"    "+a21+"    "+a22)+"\n"+
   (a31+"    "+a32+"    "+a33+"    "+a31+"    "+a32)+"\n"+
   (a11+"    "+a12+"    "+a13+"    "+a11+"    "+a12)+"\n"+
   (a21+"    "+a22+"    "+a23+"    "+a21+"    "+a22)+"\n"+
("Second Form:")+"\n"+
 (a22+"    "+a23+"    "+a21+"    "+a22)+"\n"+
   (a32+"    "+a33+"    "+a31+"    "+a32)+"\n"+
   (a12+"    "+a13+"    "+a11+"    "+a12)+"\n"+
   (a22+"    "+a23+"    "+a21+"    "+a22);
   return x;
    }

    public String adj2x2(double a11,double a12 ,double a21,double a22){
         String x=("Adjoint:")+" \n"+
              (a22+"   -"+a12+"\n-"+a21+"    "+a11);
         return x;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdjointForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdjointForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdjointForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdjointForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdjointForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
